graph LR
    Admin(("👤 Admin"))
    Manager(("👤 Manager"))
    Testeur(("👤 Testeur"))

    subgraph AUTH["Authentification"]
        UC1[Se connecter]
        UC2[Changer mot de passe]
    end

    subgraph PROJ["Gestion des Projets"]
        UC4[Creer un projet]
        UC5[Modifier un projet]
        UC6[Supprimer un projet]
        UC7[Archiver un projet]
        UC8[Valider un projet]
        UC9[Consulter les projets]
        UC10[Assigner des membres]
    end

    subgraph STRUCT["Structure de Test"]
        UC11[Creer un module]
        UC12[Creer un scenario]
        UC13[Creer cas de test]
        UC14[Importer cas depuis Excel]
    end

    subgraph EXEC["Execution"]
        UC15[Creer session de test]
        UC16[Executer un cas de test]
        UC17[Mettre a jour resultat]
    end

    subgraph ANOM["Anomalies"]
        UC19[Declarer une anomalie]
        UC20[Changer statut anomalie]
        UC22[Consulter anomalies]
    end

    subgraph REPORT["Rapports et Dashboard"]
        UC23[Tableau de bord global]
        UC25[Generer rapport PDF]
    end

    subgraph IA["Fonctionnalites IA"]
        UC30[Generer cas de test IA]
        UC31[Resume session IA]
        UC32[Gravite auto anomalie]
        UC33[Chatbot IA]
    end

    Admin --> UC1 & UC4 & UC5 & UC6 & UC7 & UC9 & UC10
    Admin --> UC11 & UC12 & UC13 & UC14
    Admin --> UC15 & UC16 & UC17
    Admin --> UC19 & UC20 & UC22
    Admin --> UC23 & UC25
    Admin --> UC30 & UC31 & UC32 & UC33

    Manager --> UC1 & UC2 & UC8 & UC9
    Manager --> UC22 & UC20
    Manager --> UC23 & UC31 & UC33

    Testeur --> UC1 & UC2 & UC9
    Testeur --> UC11 & UC12 & UC13 & UC14
    Testeur --> UC15 & UC16 & UC17
    Testeur --> UC19 & UC22
    Testeur --> UC30 & UC32 & UC33
