stateDiagram-v2
    [*] --> EN_COURS : Admin cree le projet

    EN_COURS --> TERMINE : Tests executes
    EN_COURS --> Archive : Admin archive

    TERMINE --> VALIDE : Manager valide
    TERMINE --> EN_COURS : Manager refuse
    TERMINE --> Archive : Admin archive

    VALIDE --> Archive : Admin archive
    Archive --> [*]
